### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by mauricekraus** [philipdarke/torchtime#3]
Hey, 

I noticed that the project appears to be inactive. I was wondering if you're still maintaining it?
If you're not, I would be happy to lend a hand in maintaining and improving the project.
In fact, I've already created my own [fork](https://github.com/mauricekraus/torchtime/tree/next) of the project that includes some cool features I think could be useful to the community.
So if you're not actively working on the repository anymore, I'd love to take over and keep the project alive!

**Comment by philipdarke** [comment]
Thanks for your comment. I am still maintaining the project. I've been focussed on another piece of work but am now picking this up again. It would be great to collaborate and build in the features you've been working on. Let me know if you'd be interested!

**Comment by mauricekraus** [comment]
Cool, I am not available till Tuesday, but after that I will try to come up with a structured pull request.

**Comment by philipdarke** [comment]
@mauricekraus Are you still planning on making a pull request? If not, I'll close the issue.
